"""
TALendingSwapWETH Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import TALendingSwapWETHStrategy
except ImportError:
    from strategy import TALendingSwapWETHStrategy

__all__ = [
    "TALendingSwapWETHStrategy",
]
